### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by IgorGanapolsky** [operasoftware/upstreamtools#9]
Hi,
I am following your directions in the README to install repo.  Upon running
`pip install -r requirements.txt`
I get an error:

> Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/xn/b4zwt34x6n32d2dr2f11zh7h0000gq/T/pip-build-n6WAOn/MarkupSafe/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/xn/b4zwt34x6n32d2dr2f11zh7h0000gq/T/pip-VlRhpw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xn/b4zwt34x6n32d2dr2f11zh7h0000gq/T/pip-build-n6WAOn/MarkupSafe/

Please advise,
Igor

**Comment by odinho** [comment]
This seems to be something wrong with your setup. MarkupSafe has trouble installing, it's not related to the tools themselves.

Would close if I still could :)
